<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime"
    nsURI="http://runtime/1.0" nsPrefix="runtime">
  <eClassifiers xsi:type="ecore:EClass" name="MSValue" eSuperTypes="#//AbstractValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ValueToIntegerMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceMarking" eSuperTypes="#//AbstractMarking">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msValue" lowerBound="1"
        eType="#//MSValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" lowerBound="1" eType="ecore:EClass ../../org.pnml.tools.epnk.pntypes.hlpng.pntd/model/HLPNGDefinition.ecore#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirty" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetMarking" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//NetAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="markings" upperBound="-1"
        eType="#//AbstractMarking" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueToIntegerMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//AbstractValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" upperBound="-1"
        eType="#//AbstractValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractValue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sort" lowerBound="1" eType="ecore:EClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Sort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeVariable" eSuperTypes="#//AbstractValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMarking" abstract="true" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation"/>
</ecore:EPackage>
