#! /bin/bash

for i in *.svg;
do
    if [ -e "$i" ]
    then
	B=`basename $i .svg`;
	rsvg-convert $i -f pdf -o $B.pdf;
    fi 
done

for i in *.eps;
do
    if [ -e "$i" ]
    then
	epstopdf $i;
    fi
done

