<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="networkmodel"
    nsURI="http://org.pnml.tools/network" nsPrefix="networkmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" upperBound="-1"
        eType="#//NetworkObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true" eSuperTypes="#//NetworkObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="#//AbstractEdge"
        eOpposite="#//AbstractEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//AbstractEdge"
        eOpposite="#//AbstractEdge/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaNode" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="OmegaNode" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEdge" abstract="true" eSuperTypes="#//NetworkObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedEdge" eSuperTypes="#//AbstractEdge"/>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedEdge" eSuperTypes="#//AbstractEdge"/>
</ecore:EPackage>
