<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="numberRuntime"
    nsURI="http://numberruntime/1.0" nsPrefix="numberruntime">
  <eClassifiers xsi:type="ecore:EClass" name="NumberValue" abstract="true" eSuperTypes="runtime.ecore#//AbstractValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntValue" eSuperTypes="#//NumberValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="PosValue" eSuperTypes="#//NumberValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="NatValue" eSuperTypes="#//NumberValue"/>
</ecore:EPackage>
